
/*CREATE TABLE IF NOT EXISTS PROVINCIA(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
NOMBRE VARCHAR(20) NOT NULL,
CONSTRAINT ID_PROVINCIA_PK PRIMARY KEY(ID)
);
INSERT INTO PROVINCIA (NOMBRE) VALUES ('ÁLAVA');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('ALBACETE');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('ALICANTE');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('ALMERIA');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('AVILA');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('BADAJOZ');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('BALEARES');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('BARCELONA');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('MÁLAGA');

CREATE TABLE IF NOT EXISTS ALUMNO(
DNI CHAR(9) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(12) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIAID INTEGER NOT NULL,
CONSTRAINT DNI_ALUMNO_PK PRIMARY KEY(DNI),
CONSTRAINT ID_PROVINCIA_FK FOREIGN KEY (PROVINCIAID) REFERENCES PROVINCIA(ID)
);*/


/*CREATE TABLE IF NOT EXISTS CURSO(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
NOMBRE VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
DURACION INTEGER NOT NULL,
CERTIFICACION VARCHAR(100) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NOT NULL,
PROVEEDOR VARCHAR(20) NOT NULL,
NUM_ASISTENTES INTEGER NOT NULL,
TIPO VARCHAR(40) CHECK( TIPO IN('Oficial', 'Online', 'Vídeo bajo demanda')) NOT NULL,
BECA BOOLEAN NOT NULL,
IMPORTE NUMERIC(8,2) NOT NULL,
CONSTRAINT ID_CURSO_PK PRIMARY KEY(ID)
);

INSERT INTO CURSO (NOMBRE,CATEGORIA,DURACION,CERTIFICACION,FECHA_INICIO,FECHA_FIN,PROVEEDOR,NUM_ASISTENTES,TIPO,BECA,IMPORTE)
 VALUES ('DAM','SUPERIOR',7,'NO','2020-08-13','2021-08-15','2',5,'Oficial',TRUE, 1339.0);

CREATE TABLE MATRICULA(
    ALUMNO_DNI CHAR(9) NOT NULL,
    CURSO_ID INTEGER NOT NULL,
    TIPO_MATRICULA VARCHAR(30) CHECK( TIPO_MATRICULA IN('Ordinaria', 'Repetidor','Familia numerosa')) NOT NULL,
    FECHA DATE NOT NULL,
    DOCUMENTACION BOOLEAN NOT NULL,
    CERTIFICADO BOOLEAN NOT NULL,
    IMPORTE_ABONADO NUMERIC(8,2) NOT NULL,
    CONSTRAINT ID_MATRICULA_PK PRIMARY KEY (ALUMNO_DNI,CURSO_ID),
    CONSTRAINT DNI_ALUMNO_FK FOREIGN KEY (ALUMNO_DNI) REFERENCES ALUMNO(DNI),
    CONSTRAINT ID_CURSO_FK FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);*/

INSERT INTO MATRICULA 
VALUES ('6382648U',0,'Ordinaria','2020-08-13',FALSE, TRUE,450);