CREATE TABLE PROVINCIA(
        ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
        NOMBRE VARCHAR(20) NOT NULL,
        CONSTRAINT ID_PROVINCIA_PK PRIMARY KEY(ID)
);

INSERT INTO PROVINCIA (NOMBRE) VALUES ('Álava');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Albacete');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Alacant');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Almería');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Ávila');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Badajoz');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Illes Balears');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Barcelona');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Burgos');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cáceres');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cádiz');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Castelló');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Ciudad Real');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Córdoba');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('A Coruña');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cuenca');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Girona');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Granada');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Guadalajara');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Gipuzkoa');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Huelva');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Huesca');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Jaén');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('León');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Lleida');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('La Rioja');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Lugo');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Madrid');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Málaga');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Murcia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Nafarroa');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Ourense');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Asturias');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Palencia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Las Palmas');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Pontevedra');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Salamanca');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Sta. Cruz de Tenerife');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Cantabria');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Segovia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Sevilla');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Soria');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Tarragona');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Teruel');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Toledo');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Valéncia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Valladolid');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Bizkaia');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Zamora');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Zaragoza');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Ceuta');
INSERT INTO PROVINCIA (NOMBRE) VALUES ('Melilla');

CREATE TABLE ALUMNO(
        DNI CHAR(9) NOT NULL,
        NOMBRE VARCHAR(50) NOT NULL,
        DIRECCION VARCHAR(150) NOT NULL,
        TELEFONO VARCHAR(12) NOT NULL,
        LOCALIDAD VARCHAR(50) NOT NULL,
        PROVINCIAID INTEGER NOT NULL,
        CONSTRAINT DNI_ALUMNO_PK PRIMARY KEY(DNI),
        CONSTRAINT ID_PROVINCIA_FK FOREIGN KEY (PROVINCIAID) REFERENCES PROVINCIA(ID)
);

INSERT INTO ALUMNO (DNI,NOMBRE,DIRECCION,TELEFONO,LOCALIDAD,PROVINCIAID) VALUES ('63825648U','PEPE','ALCATRAN 5','+34603758134','COÍN',1);
INSERT INTO ALUMNO (DNI,NOMBRE,DIRECCION,TELEFONO,LOCALIDAD,PROVINCIAID) VALUES ('74925643R','LOLA','TRAMONTINA F','+57698658211','MARBELLA',2);


CREATE TABLE CURSO(
        ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
        NOMBRE VARCHAR(50) NOT NULL,
        CATEGORIA VARCHAR(30) NOT NULL,
        DURACION INTEGER NOT NULL,
        CERTIFICACION VARCHAR(100) NOT NULL,
        FECHA_INICIO DATE NOT NULL,
        FECHA_FIN DATE NOT NULL,
        PROVEEDOR VARCHAR(100) NOT NULL,
        INSTRUCTOR VARCHAR(50),
        NUM_ASISTENTES INTEGER NOT NULL,
        TIPO VARCHAR(40) CHECK( TIPO IN('Oficial', 'Online', 'Vídeo bajo demanda')) NOT NULL,
        BECA BOOLEAN NOT NULL,
        IMPORTE NUMERIC(8,2) NOT NULL,
        CONSTRAINT ID_CURSO_PK PRIMARY KEY(ID)
);

/*CREATE TABLE INSTRUCTOR(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL,
    LOCALIDAD VARCHAR(50) NOT NULL,
    PROVINCIAID INTEGER NOT NULL,
    CURSOID INTEGER NOT NULL,
);*/

INSERT INTO CURSO (NOMBRE, CATEGORIA, DURACION, CERTIFICACION, FECHA_INICIO, FECHA_FIN, PROVEEDOR, INSTRUCTOR, NUM_ASISTENTES, TIPO, BECA, IMPORTE)
 VALUES ('DAM','SUPERIOR',7,'NO','2020-08-13','2021-08-15','IES LOS MONTECILLOS', 'ELENA DELGADO',5,'Oficial',TRUE, 1339.0);

CREATE TABLE MATRICULA(
        ALUMNO_DNI CHAR(9) NOT NULL,
        CURSO_ID INTEGER NOT NULL,
        TIPO_MATRICULA VARCHAR(30) CHECK( TIPO_MATRICULA IN('Ordinaria', 'Repetidor','Familia numerosa')) NOT NULL,
        FECHA DATE NOT NULL,
        DOCUMENTACION BOOLEAN NOT NULL,
        CERTIFICADO BOOLEAN NOT NULL,
        IMPORTE_ABONADO NUMERIC(8,2) NOT NULL,
        CONSTRAINT ID_MATRICULA_PK PRIMARY KEY (ALUMNO_DNI,CURSO_ID),
        CONSTRAINT DNI_ALUMNO_FK FOREIGN KEY (ALUMNO_DNI) REFERENCES ALUMNO(DNI),
        CONSTRAINT ID_CURSO_FK FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);

INSERT INTO MATRICULA 
VALUES ('6382648U',0,'Ordinaria','2020-08-13',FALSE, TRUE,450);